load("@bazel_skylib//:bzl_library.bzl", "bzl_library")
load(":generate_path_test.bzl", "dep_import_path_test", "repo_rel_from_short_path_test")

package(default_visibility = ["//visibility:public"])

bzl_library(
    name = "plugin_bzl",
    srcs = ["plugin.bzl"],
)

bzl_library(
    name = "generate_bzl",
    srcs = ["generate.bzl"],
    deps = [
        "@bazel_utils_core//internal:launcher",
        "@protoc_root_plugins//:plugins_bzl",
    ],
)

bzl_library(
    name = "format_bzl",
    srcs = ["format.bzl"],
    deps = [
        ":generate_bzl",
        "@bazel_skylib//lib:shell",
        "@bazel_utils_core//internal:launcher",
        "@bazel_utils_core//internal:workspace_tool",
    ],
)

bzl_library(
    name = "lint_bzl",
    srcs = ["lint.bzl"],
    deps = [
        ":generate_bzl",
        "@bazel_skylib//lib:shell",
        "@bazel_utils_core//internal:launcher",
        "@bazel_utils_core//internal:runfiles",
        "@bazel_utils_core//internal:workspace_cd",
        "@bazel_utils_core//internal:workspace_tool",
    ],
)

bzl_library(
    name = "buf_bzl",
    srcs = ["buf.bzl"],
    deps = [
        ":format_bzl",
        ":generate_bzl",
        ":lint_bzl",
        ":plugin_bzl",
    ],
)

repo_rel_from_short_path_test(
    name = "repo_rel_from_short_path_test",
    size = "small",
)

dep_import_path_test(
    name = "dep_import_path_test",
    size = "small",
)
